modLoader="javafml"
loaderVersion="[${javafml_min},${javafml_max})"
license="MIT"

[[mods]]
    modId="${mod_id}"
    version="${version}"
    displayName="${mod_title}"
    authors="${mod_author}"
    description='''
Night will be skipped when enough players are in bed.
Command "/playersInBed" can be used to get mod status or configure mod options.  
    '''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version_min},${forge_version_max})"
    ordering="NONE"
    side="SERVER"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft_version_min},${minecraft_version_max})"
    ordering="NONE"
    side="SERVER"

