modLoader="javafml"
loaderVersion="[${javafml_min},${javafml_max})"
license="MIT"

[[mods]]
    modId="playersinbed"
    version="${version}"
    displayName="Players in Bed"
    authors="Vlaeh"
    description='''
A little of this, a little of that, a lot of tinkering, and a lot of tools
    '''

[[dependencies.playersinbed]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version_min},${forge_version_max})"
    ordering="NONE"
    side="BOTH"

[[dependencies.playersinbed]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft_version_min},${minecraft_version_max})"
    ordering="NONE"
    side="BOTH"

